### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by hkdobrev** [mondora/handbook#2]
Could you please add a table of contents or split contents into multiple files with links to them? It would make it easier to find the information a person is most interested in.

**Comment by kirstjn** [comment]
Hi,
that's actually a good idea, we will work on it ;)

**Comment by hkdobrev** [comment]
Different examples:

- https://github.com/clippings/join-us#readme
- https://github.com/basecamp/handbook#sections
- https://github.com/madetech/handbook#table-of-contents

I'd also appreciate a PR to include your handbook in https://github.com/hkdobrev/awesome-handbooks once this is resolved! Thank you!

**Comment by hkdobrev** [comment]
🙌 Thanks! I've added Mondora's handbook to https://github.com/hkdobrev/awesome-handbooks

**Comment by kirstjn** [comment]
Great! Thank you :D

Kirsten

*:mondora srl sb *
a TeamSystem company and Certified B Corporation
<http://www.bcorporation.net/community/mondora-srl>
Kirsten Ruffoni|Benefit & Impact Strategy Specialist|+39 0342 1856 456 |
skype: kirsten.jane87 | blog:bcalmbcorp.com | personal blog: kirstjn.com |
twitter: @kirstjn <http://twitter.com/kirstjn>
Subscribe to B Calm B Corp
<https://app.getresponse.com/site2/customercommunication?u=sgym&webforms_id=IR1x>
Think before you print.
